[versions]
kafka = "2.8.2"
guava = "33.1.0-jre"
jackson = "2.17.0"
jersey = "3.1.6"
jetty = "12.0.8"
curator = "5.4.0"
dropwizard-metrics = "4.2.25"
micrometer-metrics = "1.13.0"
wiremock = "3.9.0"
spock = "2.4-M4-groovy-4.0"
groovy = "4.0.21"
avro = "1.11.3"
json2avro = "0.2.14"
# TODO: newest version requires subject alternative name in a certificate during host verification, current test cert does not have one
okhttp = "3.9.1"
undertow = "2.3.12.Final"
spring-web = "6.1.6"
failsafe = "3.3.2"
junit-jupiter = "5.10.2"
testcontainers = "1.19.8"
spring = "3.2.4"
assertj = "3.25.3"
allure = "2.24.0"
slf4j = "2.0.4"
commons-lang3 = "3.14.0"
axion-release = "1.21.0"
nexus-publish = "1.0.0"
node-gradle = "7.0.2"
jmh = "0.7.2"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }

# Allure
allure-bom = { module = "io.qameta.allure:allure-bom", version.ref = "allure" }
allure-spock2 = { module = "io.qameta.allure:allure-spock2" }
allure-junit-platform = { module = "io.qameta.allure:allure-junit-platform" }
allure-junit5 = { module = "io.qameta.allure:allure-junit5" }

# Spock
spock-bom = { module = "org.spockframework:spock-bom", version.ref = "spock" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
spock-junit4 = { module = "org.spockframework:spock-junit4", version.ref = "spock" }
spock-spring = { module = "org.spockframework:spock-spring", version.ref = "spock" }

# Testing
junit = { module = "junit:junit", version = "4.11" }
junit-dataprovider = { module = "com.tngtech.java:junit-dataprovider", version = "1.10.0" }
mockito-core = { module = "org.mockito:mockito-core", version = "5.11.0" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version = "4.2.1" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit-jupiter" }

# Spring
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "spring" }
spring-boot-starter-jersey = { module = "org.springframework.boot:spring-boot-starter-jersey", version.ref = "spring" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring" }
spring-web = { module = "org.springframework:spring-web", version.ref = "spring-web" }
spring-webflux = { module = "org.springframework:spring-webflux", version.ref = "spring-web" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring-web" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring-web" }

# Kafka
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }

# Guava
guava = { module = "com.google.guava:guava", version.ref = "guava" }

# Jackson
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-jakarta-rs-json-provider = { module = "com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-json-provider", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-jaxrs-json-provider = { module = "com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider", version.ref = "jackson" }

# Jersey
jersey-client = { module = "org.glassfish.jersey.core:jersey-client", version.ref = "jersey" }
jersey-hk2 = { module = "org.glassfish.jersey.inject:jersey-hk2", version.ref = "jersey" }
jersey-media-json-jackson = { module = "org.glassfish.jersey.media:jersey-media-json-jackson", version.ref = "jersey" }
jersey-bean-validation = { module = "org.glassfish.jersey.ext:jersey-bean-validation", version.ref = "jersey" }
jersey-mvc-freemarker = { module = "org.glassfish.jersey.ext:jersey-mvc-freemarker", version.ref = "jersey" }
jersey-proxy-client = { module = "org.glassfish.jersey.ext:jersey-proxy-client", version.ref = "jersey" }

# Jetty
jetty-alpn-java-client = { module = "org.eclipse.jetty:jetty-alpn-java-client", version.ref = "jetty" }
jetty-http2-client-transport = { module = "org.eclipse.jetty.http2:jetty-http2-client-transport", version.ref = "jetty" }

# Curator
curator-client = { module = "org.apache.curator:curator-client", version.ref = "curator" }
curator-recipes = { module = "org.apache.curator:curator-recipes", version.ref = "curator" }
curator-test = { module = "org.apache.curator:curator-test", version.ref = "curator" }

# Metrics
dropwizard-metrics-core = { module = "io.dropwizard.metrics:metrics-core", version.ref = "dropwizard-metrics" }
micrometer-core = { module = "io.micrometer:micrometer-core", version.ref = "micrometer-metrics" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer-metrics" }

# Avro & Schema
avro = { module = "org.apache.avro:avro", version.ref = "avro" }
json2avro-converter = { module = "tech.allegro.schema.json2avro:converter", version.ref = "json2avro" }

# WireMock
wiremock-standalone = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }

# Groovy
groovy-json = { module = "org.apache.groovy:groovy-json", version.ref = "groovy" }

# OkHttp
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

# Undertow
undertow-core = { module = "io.undertow:undertow-core", version.ref = "undertow" }

# Failsafe
failsafe = { module = "dev.failsafe:failsafe", version.ref = "failsafe" }

# Testcontainers
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-spock = { module = "org.testcontainers:spock", version.ref = "testcontainers" }
testcontainers-kafka = { module = "org.testcontainers:kafka", version.ref = "testcontainers" }
testcontainers-gcloud = { module = "org.testcontainers:gcloud", version.ref = "testcontainers" }
testcontainers-toxiproxy = { module = "org.testcontainers:toxiproxy", version.ref = "testcontainers" }
testcontainers-elasticsearch = { module = "org.testcontainers:elasticsearch", version = "1.20.3" }

[plugins]
axion-release = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion-release" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
node-gradle = { id = "com.github.node-gradle.node", version.ref = "node-gradle" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh" }
